---
title: "R Notebook"
---

```{r}
library(tidyverse)
```


```
{r}
workshp_registrations
```


```
{r}
instructors_small
```

```
{r}
themes_small 
```



```{r}
# tmp_df <- workshp_registrations |> 
#   filter(year > 2019) |> 
#   left_join(instructors_small, by = c("WorkshopID" = "workshop_id")) |> 
#   left_join(themes_small, by = c("WorkshopID" = "workshop_id")) |> 
#   janitor::clean_names()

tmp_df <- read_csv("my_temp_reg.csv")
tmp_df
```


```{r}
tmp_df |> 
  select(workshop_id, attended_x_or_blank:workshop_name, email, discipline, status, acd_year:year, period:theme2, institutes_initiatives_or_program_affiliation) |> 
  ggplot(aes(workshop_date, color = presenter)) +
  geom_line(stat = "count", show.legend = FALSE)

tmp_df |> 
  select(workshop_id, attended_x_or_blank:workshop_name, email, discipline, status, acd_year:year, period:theme2, institutes_initiatives_or_program_affiliation) |> 
  ggplot(aes(y = fct_rev(fct_infreq(presenter)), fill = presenter)) +
  geom_bar(show.legend = FALSE)


```

```{r}
tmp_df |> 
  count(workshop_date) |> 
  # write_csv("worshops_over_time.csv")
  ggplot(aes(workshop_date, n)) +
  geom_line()
```

